# Generated by Django 4.0.3 on 2022-11-23 07:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='dateof',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 11, 23, 7, 4, 28, 564687, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='priority',
            field=models.TextField(default='high'),
            preserve_default=False,
        ),
    ]
