# Generated by Django 4.0.3 on 2022-11-25 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toapp', '0002_todolistitem_dateof_todolistitem_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='content1',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
